import type { Metadata } from "next";
import { setRequestLocale } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Noto_Serif_JP } from "next/font/google";
import { CartProvider } from "../../store/cart";
import "../globals.css";
import Header from "@/components/Header";
import { Footer } from "@/components/Footer";

const inter = Noto_Serif_JP({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "聚楽苑",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  // SSG対応
  setRequestLocale(locale);

  // 言語ファイルの読み込み
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          <CartProvider>
            <Header />
            <main className="container mx-auto p-4">{children}</main>
            <Footer />
          </CartProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
